#:kivy 2.3.0
BoxLayout:
    MyLayout

<MyLayout>
    orientation: 'vertical'
    Label:
        id: main_label
        font_name: 'Default'
        text: 'yes'
        markup: True
    Button:
        font_name: 'Default'
        text: '获取课表'
    Button:
        font_name: 'Default'
        text: '更新天气信息'
    Button:
        font_name: 'Default'
        text: '输出'
        on_press: root.print_result()
